config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  Rails.application.routes.draw do

  resources :items

  root 'welcome#index'
  
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item
    else
      render 'new'
    end
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to @item
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:title, :notes)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/edit.html.erb
<h1>Edit Todo Item</h1>
<%= form_for @item do |f| %>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>

<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Todo List</h1>

<%= link_to 'New Todo', new_item_path %>
<table>
  <tr>
    <th>Item</th>
    <th>Text</th>
  </tr>
  
  <% @items.each do |item| %>
  <tr>
    <td><%= item.title %></td>
    <td><%= item.notes %></td>
    <td><%= link_to 'Show', item_path(item) %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item_path(item), method: :delete %></td>
  </tr>
  <% end %>
</table>

app/views/items/new.html.erb
<h1>New Item</h1>
<%= form_for :item, url: items_path do |f| %>  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @item.notes %>
</p>

<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello!</h1>
<%= link_to 'Todo List', controller: 'items' %>